# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'real.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QDateTime, Qt
from PyQt5.QtWidgets import QMessageBox
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        # Create QTimer object
        self.timer = QTimer(MainWindow)
        # Set interval for timer (in milliseconds)
        self.timer.setInterval(1000)  # Update every 1000 milliseconds (1 second)
        # Connect timeout signal of timer to update_clock method
        self.timer.timeout.connect(self.update_clock)
        # Start the timer
        self.timer.start()
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dashboard = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Kannada")
        font.setPointSize(14)
        self.dashboard.setFont(font)
        self.dashboard.setObjectName("dashboard")
        self.sidebar = QtWidgets.QWidget(self.dashboard)
        self.sidebar.setGeometry(QtCore.QRect(-30, 0, 160, 525))
        self.sidebar.setMaximumSize(QtCore.QSize(190, 16777215))
        self.sidebar.setStyleSheet("background-color: rgb(233, 237, 237);\n"
"background-color: rgb(205, 208, 208);")
        self.sidebar.setObjectName("sidebar")
        self.Dashboard = QtWidgets.QWidget(self.sidebar)
        self.Dashboard.setGeometry(QtCore.QRect(40, 10, 111, 41))
        self.Dashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dashboard.setStyleSheet("QWidget:hover{\n"
" \n"
"    background-color: rgb(218, 222, 222);\n"
"}")
        self.Dashboard.setObjectName("Dashboard")
        self.label = QtWidgets.QLabel(self.Dashboard)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/icons8-dashboard-50.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Dashboard)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Dashboard_2 = QtWidgets.QWidget(self.sidebar)
        self.Dashboard_2.setGeometry(QtCore.QRect(40, 60, 111, 41))
        self.Dashboard_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.Dashboard_2.setStyleSheet("QWidget:hover{\n"
" \n"
"    background-color: rgb(218, 222, 222);\n"
"}")
        self.Dashboard_2.setObjectName("Dashboard_2")

        # Connect About Us button clicked signal to display_about_us method
        self.Dashboard_2.clicked.connect(self.display_about_us)

        self.label_5 = QtWidgets.QLabel(self.Dashboard_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Downloads/icons8-users-48.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        
        self.label_6 = QtWidgets.QLabel(self.Dashboard_2)
        self.label_6.setGeometry(QtCore.QRect(40, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Dashboard_3 = QtWidgets.QWidget(self.sidebar)
        self.Dashboard_3.setGeometry(QtCore.QRect(40, 110, 111, 41))
        self.Dashboard_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dashboard_3.setStyleSheet("QWidget:hover{\n"
" \n"
"    background-color: rgb(218, 222, 222);\n"
"}")
        self.Dashboard_3.setObjectName("Dashboard_3")
        self.label_7 = QtWidgets.QLabel(self.Dashboard_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Downloads/icons8-reviews-66.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Dashboard_3)
        self.label_8.setGeometry(QtCore.QRect(40, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(self.sidebar)
        self.widget.setGeometry(QtCore.QRect(40, 420, 120, 51))
        self.widget.setObjectName("widget")
        self.Dashboard_4 = QtWidgets.QWidget(self.widget)
        self.Dashboard_4.setGeometry(QtCore.QRect(0, 10, 111, 41))
        self.Dashboard_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dashboard_4.setStyleSheet("QWidget:hover{\n"
" \n"
"    background-color: rgb(218, 222, 222);\n"
"}")
        self.Dashboard_4.setObjectName("Dashboard_4")
        self.label_15 = QtWidgets.QLabel(self.Dashboard_4)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../Downloads/icons8-copyright-material-sharp/icons8-copyright-48.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.Dashboard_4)
        self.label_18.setGeometry(QtCore.QRect(40, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.widget_2 = QtWidgets.QWidget(self.dashboard)
        self.widget_2.setGeometry(QtCore.QRect(140, 0, 641, 251))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("border-color: rgb(197, 200, 200);\n"
"background-color: rgb(226, 78, 53);\n"
"background-color: rgb(255, 46, 59);\n"
"background-color: rgb(190, 190, 191);\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 621, 91))
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: white;\n"
"background-color: rgb(21, 150, 203);\n"
"font: 700 48pt \"Apple SD Gothic Neo\";")
        self.label_19.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(10, 100, 200, 121))
        self.widget_4.setStyleSheet("border-top-color: rgb(208, 64, 40);\n"
"background-color:white;\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.label_3.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 201, 51))
        self.label_4.setStyleSheet("font: 30pt \"Apple Braille\";\n"
"color:rgb(255, 46, 49)")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setGeometry(QtCore.QRect(120, -10, 81, 81))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../../Downloads/icons8-danger-48.png"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(220, 100, 200, 121))
        self.widget_6.setStyleSheet("border-top-color: rgb(208, 64, 40);\n"
"background-color:white;\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_10.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_10.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 201, 51))
        self.label_12.setStyleSheet("font: 30pt \"Apple Braille\";\n"
"\n"
"color: rgb(33, 193, 49);")
        self.label_12.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setGeometry(QtCore.QRect(440, 10, 161, 31))
        self.label_14.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_24 = QtWidgets.QLabel(self.widget_6)
        self.label_24.setGeometry(QtCore.QRect(127, 0, 61, 61))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../../Downloads/icons8-tick-64.png"))
        self.label_24.setObjectName("label_24")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(430, 100, 200, 121))
        self.widget_7.setStyleSheet("border-top-color: rgb(208, 64, 40);\n"
"background-color:white;\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.label_11.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.widget_7)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 201, 51))
        self.label_16.setStyleSheet("font: 30pt \"Apple Braille\";\n"
"color:rgb(255, 46, 49)")
        self.label_16.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_7)
        self.label_17.setGeometry(QtCore.QRect(650, 10, 161, 31))
        self.label_17.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        self.label_20.setGeometry(QtCore.QRect(147, 0, 51, 61))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("../../Downloads/icons8-danger-48.png"))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_7)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.label_21.setStyleSheet("font: 24pt \"Al Bayan\";")
        self.label_21.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_7)
        self.label_22.setGeometry(QtCore.QRect(120, 0, 81, 61))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("../../Downloads/icons8-danger-48.png"))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(530, 20, 91, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"font: 18pt \"Apple Braille\";\n"
"color:white;\n"
"border-radius:1px;\n"
"background-color: rgb(31, 191, 38);\n"
"}\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(28, 145, 36);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/icons8-home-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.widget_3 = QtWidgets.QWidget(self.dashboard)
        self.widget_3.setGeometry(QtCore.QRect(130, 280, 641, 241))
        self.widget_3.setObjectName("widget_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(10, -10, 641, 251))
        self.widget_5.setStyleSheet("border-color: rgb(197, 200, 200);\n"
"background-color: rgb(226, 78, 53);\n"
"background-color: rgb(255, 46, 59);\n"
"background-color: rgb(190, 190, 191);\n"
"\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_25 = QtWidgets.QLabel(self.widget_5)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 611, 61))
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: black;\n"
"background-color: rgb(174, 177, 177);\n"
"font: 700 28pt \"Apple SD Gothic Neo\";")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setGeometry(QtCore.QRect(50, 120, 121, 41))
        self.label_26.setStyleSheet("font: italic 24pt \"AkayaTelivigala\";\n"
"border-color: rgb(78, 255, 110);\n"
"font:  bold 28pt \"Avenir\";")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        self.label_27.setGeometry(QtCore.QRect(190, 120, 121, 41))
        self.label_27.setStyleSheet("font: italic 24pt \"AkayaTelivigala\";\n"
"font:  bold 28pt \"Avenir\";")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setGeometry(QtCore.QRect(330, 120, 121, 41))
        self.label_28.setStyleSheet("font: italic 24pt \"AkayaTelivigala\";\n"
"font:  bold 28pt \"Avenir\";")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.widget_5)
        self.label_29.setGeometry(QtCore.QRect(470, 120, 121, 41))
        self.label_29.setStyleSheet("font: italic 24pt \"AkayaTelivigala\";\n"
"font:  bold 28pt \"Avenir\";")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setGeometry(QtCore.QRect(340, 170, 101, 31))
        self.label_32.setStyleSheet("color:white;\n"
"color: rgb(255, 36, 47);\n"
"font: 700 48pt \"Kaiti TC\";")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.widget_5)
        self.label_34.setGeometry(QtCore.QRect(200, 170, 101, 31))
        self.label_34.setStyleSheet("color:white;\n"
"color: rgb(255, 36, 47);\n"
"font: 700 48pt \"Kaiti TC\";")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.widget_5)
        self.label_36.setGeometry(QtCore.QRect(70, 170, 101, 31))
        self.label_36.setStyleSheet("color:white;\n"
"color: rgb(255, 36, 47);\n"
"font: 700 48pt \"Kaiti TC\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget_5)
        self.label_37.setGeometry(QtCore.QRect(480, 170, 101, 31))
        self.label_37.setStyleSheet("color:white;\n"
"color: rgb(255, 36, 47);\n"
"font: 700 48pt \"Kaiti TC\";")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setGeometry(QtCore.QRect(160, 160, 41, 41))
        self.label_9.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.widget_5)
        self.label_13.setGeometry(QtCore.QRect(290, 160, 41, 41))
        self.label_13.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_13.setObjectName("label_13")
        self.label_30 = QtWidgets.QLabel(self.widget_5)
        self.label_30.setGeometry(QtCore.QRect(430, 170, 41, 41))
        self.label_30.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_5)
        self.label_31.setGeometry(QtCore.QRect(440, 160, 41, 41))
        self.label_31.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.widget_5)
        self.label_33.setGeometry(QtCore.QRect(290, 170, 41, 41))
        self.label_33.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.widget_5)
        self.label_35.setGeometry(QtCore.QRect(430, 170, 41, 41))
        self.label_35.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_35.setObjectName("label_35")
        self.label_38 = QtWidgets.QLabel(self.widget_5)
        self.label_38.setGeometry(QtCore.QRect(160, 170, 41, 41))
        self.label_38.setStyleSheet("font: 26pt \"Academy Engraved LET\";\n"
"font: 36pt \"Apple Braille\";")
        self.label_38.setObjectName("label_38")
        self.line = QtWidgets.QFrame(self.widget_5)
        self.line.setGeometry(QtCore.QRect(50, 120, 550, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_5)
        self.line_2.setGeometry(QtCore.QRect(50, 120, 3, 100))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget_5)
        self.line_3.setGeometry(QtCore.QRect(600, 120, 3, 100))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget_5)
        self.line_4.setGeometry(QtCore.QRect(50, 220, 550, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_9 = QtWidgets.QFrame(self.widget_5)
        self.line_9.setGeometry(QtCore.QRect(180, 120, 3, 100))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.widget_5)
        self.line_10.setGeometry(QtCore.QRect(310, 120, 3, 100))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.widget_5)
        self.line_11.setGeometry(QtCore.QRect(450, 120, 3, 100))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout.addWidget(self.dashboard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def update_clock(self):
        # Calculate the elapsed time since COVID-19 arrival
        covid_start_date = QDateTime.fromString("2019-12-31T00:00:00", Qt.ISODate)  # Assuming COVID-19 started on Dec 31, 2019
        current_date = QDateTime.currentDateTime()
        elapsed_seconds = covid_start_date.secsTo(current_date)

        # Calculate days, hours, minutes, and seconds
        days = elapsed_seconds // (24 * 3600)
        hours = (elapsed_seconds % (24 * 3600)) // 3600
        minutes = (elapsed_seconds % 3600) // 60
        seconds = elapsed_seconds % 60
        # Update labels with the calculated values
        self.label_36.setText(str(days))
        self.label_34.setText(str(hours))
        self.label_32.setText(str(minutes))
        self.label_37.setText(str(seconds))

    def display_about_us(self):
        # Create a message box with information about developers
        about_us_text = "Developed by:\n1. Riya Sahu\n2. Sejal Agrawal\n3. Suyash Khare\n4. Yashi Agarwal"
        msg_box = QMessageBox()
        msg_box.setWindowTitle("About Us")
        msg_box.setText(about_us_text)
        msg_box.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Dashboard"))
        self.label_6.setText(_translate("MainWindow", "About Us"))
        self.label_8.setText(_translate("MainWindow", "Reviews"))
        self.label_18.setText(_translate("MainWindow", "Copyright"))
        self.label_19.setText(_translate("MainWindow", "  Covid-19 Dashboard"))
        self.label_3.setText(_translate("MainWindow", "Cases"))
        self.label_4.setText(_translate("MainWindow", "  +12334"))
        self.label_10.setText(_translate("MainWindow", "Recovered"))
        self.label_12.setText(_translate("MainWindow", "  +12334"))
        self.label_14.setText(_translate("MainWindow", "Cases"))
        self.label_11.setText(_translate("MainWindow", "Deaths"))
        self.label_16.setText(_translate("MainWindow", "  +1233435"))
        self.label_17.setText(_translate("MainWindow", "Cases"))
        self.label_21.setText(_translate("MainWindow", "Deaths"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.label_25.setText(_translate("MainWindow", "Time Since COVID-19 Outbreak"))
        self.label_26.setText(_translate("MainWindow", "    Days"))
        self.label_27.setText(_translate("MainWindow", " Hours"))
        self.label_28.setText(_translate("MainWindow", "Minutes"))
        self.label_29.setText(_translate("MainWindow", "Seconds"))
        self.label_32.setText(_translate("MainWindow", "11"))
        self.label_34.setText(_translate("MainWindow", "10"))
        self.label_36.setText(_translate("MainWindow", "1587"))
        self.label_37.setText(_translate("MainWindow", "47"))
        self.label_9.setText(_translate("MainWindow", "  :"))
        self.label_13.setText(_translate("MainWindow", "  :"))
        self.label_30.setText(_translate("MainWindow", "  :"))
        self.label_31.setText(_translate("MainWindow", "  :"))
        self.label_33.setText(_translate("MainWindow", "  :"))
        self.label_35.setText(_translate("MainWindow", "  :"))
        self.label_38.setText(_translate("MainWindow", "  :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
